apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brahimsayah/calculator.git
    targetRevision: HEAD
    path: book
  destination:
    server: https://kubernetes.default.svc
    namespace: default
